---
# PHP

- name: PHP 5.5 Custom Repo
  apt_repository: repo='ppa:ondrej/php5' update_cache=yes

- name: PHP and Modules
  apt: pkg={{ item }} state=latest
  tags: common
  with_items:
    - php5
    - php5-mysql
    - php5-gd
    - php-apc
    - php5-mcrypt
    - php5-curl
    - php5-intl
    - php5-memcached

# PHP-FPM

- name: PHP-FPM
  apt: pkg=php5-fpm state=installed

# NGINX

- name: NGINX
  apt: pkg=nginx state=installed

- name: NGINX | Copy Host Config
  template: src=../files/nginx_site.conf dest=/etc/nginx/sites-available/{{ item.hostname }}.conf
  with_items: sites

- name: Remove Default Configuration
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Activate Hosts
  file: src=/etc/nginx/sites-available/{{ item.hostname }}.conf dest=/etc/nginx/sites-enabled/{{ item.hostname }}.conf state=link
  with_items: sites

# Composer

- stat: path=/usr/local/bin/composer
  register: composer_folder

- name: Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  when: composer_folder.stat.isdir is not defined

# Remove Apache

- name: Remove Apache
  apt: pkg=apache2 state=absent purge=yes
  notify: restart nginx
